INSERT INTO maquinas (nombre, linea, orden)
VALUES
    ('DESPALETIZADORA L1', 'L1', 1),
    ('TRANSPORTADOR DE PALETAS L1', 'L1', 2),
    ('PALETIZADORA L1', 'L1', 3),
    ('LAVADORA DE CAJAS L1', 'L1', 4),
    ('TRANSPORTADORES DE CAJAS L1', 'L1', 5),
    ('DESENCAJONADORA L1', 'L1', 6),
    ('ENCAJONADORA L1', 'L1', 7),
    ('LAVADORA DE BOTELLAS L1', 'L1', 8),
    ('INSPECTOR DE BOTELLAS VACIAS L1', 'L1', 9),
    ('LLENADORA L1', 'L1', 10),
    ('ETIQUETADORA L1', 'L1', 11),
    ('DESPALETIZADORA L2', 'L2', 12),
    ('TRANSPORTADOR DE PALETAS L2', 'L2', 13),
    ('PALETIZADORA L2', 'L2', 14),
    ('LAVADORA DE CAJAS L2', 'L2', 15),
    ('TRANSPORTADORES DE CAJAS L2', 'L2', 16),
    ('DESENCAJONADORA L2', 'L2', 17),
    ('ENCAJONADORA L2', 'L2', 18),
    ('LAVADORA DE BOTELLAS L2', 'L2', 19),
    ('INSPECTOR DE BOTELLAS VACIAS L2', 'L2', 20),
    ('LLENADORA L2', 'L2', 21),
    ('ETIQUETADORA L2', 'L2', 22)
ON CONFLICT (nombre) DO UPDATE SET
    linea = EXCLUDED.linea,
    orden = EXCLUDED.orden;

UPDATE puntos_aislamiento AS pa
SET maquina_id = m.id
FROM maquinas AS m
WHERE pa.maquina_id IS NULL
  AND m.nombre = 'DESPALETIZADORA L1'
  AND pa.id_visual IN ('PM-DEPA-E1', 'PM-DEPA-N1', 'PM-DEPA-L1', 'PM-DEPA-E2');

INSERT INTO puntos_aislamiento (maquina_id, id_visual, descripcion, orden, foto_url, blueprint_x, blueprint_y, color_hex)
SELECT m.id, v.id_visual, v.descripcion, v.orden, v.foto_url, v.blueprint_x, v.blueprint_y, v.color_hex
FROM (
    VALUES
        ('DESPALETIZADORA L1', 'PM-DEPA-E1', 'Tablero electrico', 1, '', 83, 79, '#d62828'),
        ('DESPALETIZADORA L1', 'PM-DEPA-N1', 'Ingreso de aire comprimido', 2, '', 64, 25, '#1d4ed8'),
        ('DESPALETIZADORA L1', 'PM-DEPA-L1', 'Ingreso de agua para lubricacion', 3, '', 42, 46, '#16a34a'),
        ('DESPALETIZADORA L1', 'PM-DEPA-E2', 'RUN del HMI de la maquina', 4, '', 34, 60, '#ef4444'),
        ('TRANSPORTADOR DE PALETAS L1', 'PM-TP-E1', 'Tablero electrico', 1, '', NULL, NULL, '#d62828'),
        ('TRANSPORTADOR DE PALETAS L1', 'PM-TP-A1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 2, '', NULL, NULL, '#1d4ed8'),
        ('TRANSPORTADOR DE PALETAS L1', 'PM-TP-A2', 'Ingreso de aire comprimido al centrador de paletas', 3, '', NULL, NULL, '#1d4ed8'),
        ('PALETIZADORA L1', 'PM-PALE-E1', 'Tablero electrico', 1, '', NULL, NULL, '#d62828'),
        ('PALETIZADORA L1', 'PM-PALE-A1', 'Ingreso de aire comprimido', 2, '', NULL, NULL, '#1d4ed8'),
        ('PALETIZADORA L1', 'PM-PALE-L1', 'Ingreso de agua para lubricacion', 3, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE CAJAS L1', 'LAVADORA DE CAJAS', 'Tablero electrico', 1, '', NULL, NULL, '#64748b'),
        ('LAVADORA DE CAJAS L1', 'PM-LC-A1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 2, '', NULL, NULL, '#1d4ed8'),
        ('LAVADORA DE CAJAS L1', 'PM-LC-AG1', 'Ingreso de agua general', 3, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE CAJAS L1', 'PM-LC-AN1', 'Ingreso de agua nanofiltrada', 4, '', NULL, NULL, '#2563eb'),
        ('LAVADORA DE CAJAS L1', 'HMI-LC', 'Encendido de lavadora de cajas', 5, '', NULL, NULL, '#16a34a'),
        ('TRANSPORTADORES DE CAJAS L1', 'PM-TC-E1', 'Tablero electrico', 1, '', NULL, NULL, '#d62828'),
        ('TRANSPORTADORES DE CAJAS L1', 'PM-TC-A1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 2, '', NULL, NULL, '#1d4ed8'),
        ('TRANSPORTADORES DE CAJAS L1', 'PM-TC-L1', 'Ingreso de agua para lubricacion', 3, '', NULL, NULL, '#16a34a'),
        ('DESENCAJONADORA L1', 'PM-DES-E1', 'Tablero electrico', 1, '', NULL, NULL, '#d62828'),
        ('DESENCAJONADORA L1', 'PM-DES-A1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 2, '', NULL, NULL, '#1d4ed8'),
        ('DESENCAJONADORA L1', 'PM-DES-L1', 'Ingreso de agua para lubricacion', 3, '', NULL, NULL, '#16a34a'),
        ('DESENCAJONADORA L1', 'PM-DES-L2', 'Ingreso de agua para lubricacion desencajonadora - mesa de carga', 4, '', NULL, NULL, '#16a34a'),
        ('ENCAJONADORA L1', 'PM-ENC-E1', 'Tablero electrico', 1, '', NULL, NULL, '#d62828'),
        ('ENCAJONADORA L1', 'PM-ENC-A1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 2, '', NULL, NULL, '#1d4ed8'),
        ('ENCAJONADORA L1', 'PM-ENC-L1', 'Ingreso de agua para lubricacion', 3, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE BOTELLAS L1', 'PM-LB-E1', 'Tablero electrico', 1, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE BOTELLAS L1', 'PM-LB-A1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 2, '', NULL, NULL, '#1d4ed8'),
        ('LAVADORA DE BOTELLAS L1', 'PM-LB-L1', 'Ingreso de agua para lubricacion', 3, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE BOTELLAS L1', 'PM-LB-SC1', 'Ingreso de soda caustica', 4, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE BOTELLAS L1', 'PM-LB-DC1', 'Ingreso de dioxido de cloro', 5, '', NULL, NULL, '#ea580c'),
        ('LAVADORA DE BOTELLAS L1', 'PM-LB-AB1', 'Ingreso de agua ablandada', 6, '', NULL, NULL, '#7c3aed'),
        ('LAVADORA DE BOTELLAS L1', 'PM-LB-V1', 'Ingreso vapor de agua', 7, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE BOTELLAS L1', 'HMI-LB', 'HMI de control de calentamiento de lavadora', 8, '', NULL, NULL, '#16a34a'),
        ('INSPECTOR DE BOTELLAS VACIAS L1', 'PM-IBV-E1', 'Tablero electrico', 1, '', NULL, NULL, '#d62828'),
        ('INSPECTOR DE BOTELLAS VACIAS L1', 'PM-IBV-A1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 2, '', NULL, NULL, '#1d4ed8'),
        ('INSPECTOR DE BOTELLAS VACIAS L1', 'PM-IBV-L1', 'Ingreso de agua para lubricacion', 3, '', NULL, NULL, '#16a34a'),
        ('INSPECTOR DE BOTELLAS VACIAS L1', 'PM-IBV-AB1', 'Ingreso de agua para duchas de pico', 4, '', NULL, NULL, '#7c3aed'),
        ('INSPECTOR DE BOTELLAS VACIAS L1', 'PM-IBV-AB2', 'Ingreso de agua para duchas del alineador', 5, '', NULL, NULL, '#7c3aed'),
        ('INSPECTOR DE BOTELLAS VACIAS L1', 'PM-IBV-E2', 'Estractores', 6, '', NULL, NULL, '#d62828'),
        ('INSPECTOR DE BOTELLAS VACIAS L1', 'HMI-IBV', 'Tranportadores de botellas', 7, '', NULL, NULL, '#d62828'),
        ('LLENADORA L1', 'PM-LLEN-E1', 'Tablero electrico', 1, '', NULL, NULL, '#16a34a'),
        ('LLENADORA L1', 'PM-LLEN-A1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 2, '', NULL, NULL, '#1d4ed8'),
        ('LLENADORA L1', 'PM-LLEN-AB1', 'Ingreso de agua Ablandada para el proceso', 3, '', NULL, NULL, '#7c3aed'),
        ('LLENADORA L1', 'PM-LLEN-CO2-1', 'Ingreso de C02', 4, '', NULL, NULL, '#0ea5e9'),
        ('LLENADORA L1', 'PM-LLEN-V1', 'Ingreso de vapor de agua', 5, '', NULL, NULL, '#16a34a'),
        ('ETIQUETADORA L1', 'PM-ETIQ-E1', 'Tablero electrico', 1, '', NULL, NULL, '#d62828'),
        ('ETIQUETADORA L1', 'PM-ETIQ-A1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 2, '', NULL, NULL, '#1d4ed8'),
        ('ETIQUETADORA L1', 'PM-ETIQ-L1', 'Ingreso de agua para lubricacion', 3, '', NULL, NULL, '#16a34a'),
        ('ETIQUETADORA L1', 'HMI-ETIQ', 'Transportadores de entra y salida de etiquetadora', 4, '', NULL, NULL, '#d62828'),
        ('DESPALETIZADORA L2', 'PM-DEPA-E1', 'Tablero electrico', 1, '', NULL, NULL, '#d62828'),
        ('DESPALETIZADORA L2', 'PM-DEPA-E2', 'Tablero electrico', 2, '', NULL, NULL, '#d62828'),
        ('DESPALETIZADORA L2', 'PM-DEPA-E3', 'Paro de Maquina desde el HMI', 3, '', NULL, NULL, '#d62828'),
        ('DESPALETIZADORA L2', 'PM-DEPA-N1', 'Ingreso de aire comprimido', 4, '', NULL, NULL, '#64748b'),
        ('DESPALETIZADORA L2', 'PM-DEPA-L1', 'Ingreso de agua para lubricacion', 5, '', NULL, NULL, '#16a34a'),
        ('TRANSPORTADOR DE PALETAS L2', 'PM-TP-E1', 'Tablero electrico', 1, '', NULL, NULL, '#d62828'),
        ('TRANSPORTADOR DE PALETAS L2', 'PM-TP-N1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 2, '', NULL, NULL, '#64748b'),
        ('TRANSPORTADOR DE PALETAS L2', 'PM-TP-N2', 'Ingreso de aire comprimido al centrador de paletas', 3, '', NULL, NULL, '#64748b'),
        ('PALETIZADORA L2', 'PM-PALE-E1', 'Tablero electrico', 1, '', NULL, NULL, '#d62828'),
        ('PALETIZADORA L2', 'PM-PALE-E2', 'Paro de Maquina desde el HMI', 2, '', NULL, NULL, '#d62828'),
        ('PALETIZADORA L2', 'PM-PALE-N1', 'Ingreso de aire comprimido', 3, '', NULL, NULL, '#64748b'),
        ('PALETIZADORA L2', 'PM-PALE-L1', 'Ingreso de agua para lubricacion', 4, '', NULL, NULL, '#16a34a'),
        ('PALETIZADORA L2', 'HMI-TC-E2', 'Arranque-Parada de Transportadores de cajas', 5, '', NULL, NULL, '#d62828'),
        ('LAVADORA DE CAJAS L2', 'PM-LC-E1', 'Tablero electrico', 1, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE CAJAS L2', 'PM-LC-E2', 'Paro de Maquina desde el HMI', 2, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE CAJAS L2', 'PM-LC-N1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 3, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE CAJAS L2', 'PM-LC-AG1', 'Ingreso de agua general', 4, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE CAJAS L2', 'PM-LC-AN1', 'Ingreso de agua nanofiltrada', 5, '', NULL, NULL, '#2563eb'),
        ('LAVADORA DE CAJAS L2', 'PM-LC-L1', 'Sistema de dosificacion de lubricante zona gris', 6, '', NULL, NULL, '#16a34a'),
        ('TRANSPORTADORES DE CAJAS L2', 'PM-TC-E1', 'Tablero electrico', 1, '', NULL, NULL, '#d62828'),
        ('TRANSPORTADORES DE CAJAS L2', 'HMI-TC-E2', 'Arranque-Parada de Transportadores de cajas', 2, '', NULL, NULL, '#d62828'),
        ('TRANSPORTADORES DE CAJAS L2', 'PM-TC-N1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 3, '', NULL, NULL, '#64748b'),
        ('TRANSPORTADORES DE CAJAS L2', 'PM-TC-N2', 'Ingreso de aire comprimido a la unidad de mantenimiento', 4, '', NULL, NULL, '#64748b'),
        ('TRANSPORTADORES DE CAJAS L2', 'PM-TC-N3', 'Ingreso de aire comprimido a la unidad de mantenimiento', 5, '', NULL, NULL, '#64748b'),
        ('TRANSPORTADORES DE CAJAS L2', 'PM-TC-L1', 'Ingreso de agua para lubricacion', 6, '', NULL, NULL, '#16a34a'),
        ('DESENCAJONADORA L2', 'PM-DES-E1', 'Tablero electrico', 1, '', NULL, NULL, '#d62828'),
        ('DESENCAJONADORA L2', 'PM-DES-E2', 'Tablero electrico', 2, '', NULL, NULL, '#d62828'),
        ('DESENCAJONADORA L2', 'PM-DES-E3', 'Paro de Maquina desde el HMI', 3, '', NULL, NULL, '#d62828'),
        ('DESENCAJONADORA L2', 'PM-DES-N1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 4, '', NULL, NULL, '#64748b'),
        ('DESENCAJONADORA L2', 'PM-DES-L1', 'Ingreso de agua para lubricacion', 5, '', NULL, NULL, '#16a34a'),
        ('ENCAJONADORA L2', 'PM-ENC-E1', 'Tablero electrico', 1, '', NULL, NULL, '#d62828'),
        ('ENCAJONADORA L2', 'PM-ENC-E2', 'Tablero electrico', 2, '', NULL, NULL, '#d62828'),
        ('ENCAJONADORA L2', 'PM-ENC-E3', 'Paro de Maquina desde el HMI', 3, '', NULL, NULL, '#d62828'),
        ('ENCAJONADORA L2', 'PM-ENC-N1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 4, '', NULL, NULL, '#d62828'),
        ('ENCAJONADORA L2', 'PM-ENC-L1', 'Ingreso de agua para lubricacion', 5, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE BOTELLAS L2', 'PM-LB-E1', 'Tablero electrico', 1, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE BOTELLAS L2', 'PM-LB-E2', 'Paro de Maquina desde el HMI', 2, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE BOTELLAS L2', 'PM-LB-N1', 'Ingreso de aire comprimido a la unidad de mantenimiento - descarga', 3, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE BOTELLAS L2', 'PM-LB-N2', 'Ingreso de aire comprimido a la unidad de mantenimiento - intercambiadores', 4, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE BOTELLAS L2', 'PM-LB-N3', 'Ingreso de aire comprimido a la unidad de mantenimiento - duchas pre lavado', 5, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE BOTELLAS L2', 'PM-LB-S1', 'Ingreso de soda caustica', 6, '', NULL, NULL, '#16a34a'),
        ('LAVADORA DE BOTELLAS L2', 'PM-LB-DC1', 'Ingreso de dioxido de cloro', 7, '', NULL, NULL, '#ea580c'),
        ('LAVADORA DE BOTELLAS L2', 'PM-LB-AB1', 'Ingreso de agua ablandada', 8, '', NULL, NULL, '#7c3aed'),
        ('LAVADORA DE BOTELLAS L2', 'PM-LB-V1', 'Ingreso vapor de agua', 9, '', NULL, NULL, '#16a34a'),
        ('INSPECTOR DE BOTELLAS VACIAS L2', 'PM-IBV-E1', 'Tablero electrico', 1, '', NULL, NULL, '#d62828'),
        ('INSPECTOR DE BOTELLAS VACIAS L2', 'PM-IBV-E2', 'Tablero electrico', 2, '', NULL, NULL, '#d62828'),
        ('INSPECTOR DE BOTELLAS VACIAS L2', 'PM-IBV-E3', 'HMI - Arranque/Parada transportadores de botellas', 3, '', NULL, NULL, '#d62828'),
        ('INSPECTOR DE BOTELLAS VACIAS L2', 'PM-IBV-N1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 4, '', NULL, NULL, '#64748b'),
        ('INSPECTOR DE BOTELLAS VACIAS L2', 'PM-IBV-AB1', 'Ingreso de agua para lubricacion de guias alineador', 5, '', NULL, NULL, '#7c3aed'),
        ('LLENADORA L2', 'PM-LLEN-E1', 'Tablero electrico', 1, '', NULL, NULL, '#16a34a'),
        ('LLENADORA L2', 'PM-LLEN-E2', 'Tablero electrico', 2, '', NULL, NULL, '#16a34a'),
        ('LLENADORA L2', 'PM-LLEN-E3', 'Paro de Maquina desde el HMI', 3, '', NULL, NULL, '#16a34a'),
        ('LLENADORA L2', 'PM-LLEN-N1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 4, '', NULL, NULL, '#16a34a'),
        ('LLENADORA L2', 'PM-LLEN-AB1', 'Ingreso de agua ablandada lubricacion', 5, '', NULL, NULL, '#7c3aed'),
        ('LLENADORA L2', 'PM-LLEN-CO2-1', 'Ingreso de C02', 6, '', NULL, NULL, '#0ea5e9'),
        ('LLENADORA L2', 'PM-LLEN-V1', 'Ingreso de vapor de agua', 7, '', NULL, NULL, '#16a34a'),
        ('ETIQUETADORA L2', 'PM-ETIQ-E1', 'Tablero electrico', 1, '', NULL, NULL, '#d62828'),
        ('ETIQUETADORA L2', 'PM-ETIQ-E2', 'Tablero electrico', 2, '', NULL, NULL, '#d62828'),
        ('ETIQUETADORA L2', 'PM-ETIQ-E3', 'Paro de Maquina desde el HMI', 3, '', NULL, NULL, '#d62828'),
        ('ETIQUETADORA L2', 'PM-ETIQ-AB1', 'Ingreso de agua para lubricacion', 4, '', NULL, NULL, '#7c3aed'),
        ('ETIQUETADORA L2', 'PM-ETIQ-N1', 'Ingreso de aire comprimido a la unidad de mantenimiento', 5, '', NULL, NULL, '#d62828')
) AS v(maquina_nombre, id_visual, descripcion, orden, foto_url, blueprint_x, blueprint_y, color_hex)
JOIN maquinas AS m ON m.nombre = v.maquina_nombre
ON CONFLICT (maquina_id, id_visual) DO UPDATE SET
    descripcion = EXCLUDED.descripcion,
    orden = EXCLUDED.orden,
    foto_url = EXCLUDED.foto_url,
    blueprint_x = EXCLUDED.blueprint_x,
    blueprint_y = EXCLUDED.blueprint_y,
    color_hex = EXCLUDED.color_hex;

UPDATE registros_checklist AS rc
SET maquina_id = pa.maquina_id
FROM puntos_aislamiento AS pa
WHERE rc.maquina_id IS NULL
  AND rc.punto_id = pa.id
  AND pa.maquina_id IS NOT NULL;

INSERT INTO tipos_check (nombre, orden, grupo, descripcion_corta)
VALUES
    ('Modulacion Parada > 10 min Danos, EFC, CIP', 1, 'parada', 'Modulacion'),
    ('Fin de Produccion', 2, 'parada', 'Fin de Produccion'),
    ('Mantenimiento o Aseo', 3, 'parada', 'Mantenimiento o Aseo'),
    ('Arranque', 4, 'arranque', 'Arranque'),
    ('BrakeDown o CIP', 5, 'breakdown', 'BrakeDown o CIP')
ON CONFLICT DO NOTHING;
INSERT INTO responsables_sharp (numero_sharp, apellido, nombre, nombre_completo, equipo, linea, lider_nombre)
VALUES
    (96302071, 'PILLAJO CHINCHIN', 'ALEJANDRO PAUL', 'ALEJANDRO PAUL PILLAJO CHINCHIN', 'LOBOS', 'L1', 'PABLO SEBASTIAN BUSE VELASQUEZ'),
    (96307412, 'SARASTI DUTAN', 'ALEXIS DAVID', 'ALEXIS DAVID SARASTI DUTAN', 'TU MANTENEDOR', 'Mtto', 'LUIS GONZALO CHILLAN PILLAJO'),
    (96301259, 'ORTIZ CRUZ', 'ANABEL ROCIO', 'ANABEL ROCIO ORTIZ CRUZ', 'LOBOS', 'L1', 'PABLO SEBASTIAN BUSE VELASQUEZ'),
    (96302233, 'RAURA VALIENTE', 'ANDRES GEOVANNY', 'ANDRES GEOVANNY RAURA VALIENTE', 'ASES', 'L2', 'GONZALO VICENTE PEREZ CASERES'),
    (96301853, 'TOPON CHIGUANO', 'BLADIMIR AUGUSTO', 'BLADIMIR AUGUSTO TOPON CHIGUANO', 'ASES', 'L2', 'GONZALO VICENTE PEREZ CASERES'),
    (96302141, 'ULCO CEVALLOS', 'BYRON GERARDO', 'BYRON GERARDO ULCO CEVALLOS', 'PREMIUM', 'L2', 'SEGUNDO CLAUDIO MOROCHO YADAICELA'),
    (96300706, 'TUSA ULCO', 'CARLOS FRANCISCO', 'CARLOS FRANCISCO TUSA ULCO', 'LOBOS', 'L1', 'PABLO SEBASTIAN BUSE VELASQUEZ'),
    (96300428, 'CHUQUIN BEJARANO', 'CARLOS KENNEDY', 'CARLOS KENNEDY CHUQUIN BEJARANO', 'PREMIUM', 'L2', 'DIEGO VLADIMIR ORTIZ CENTENO'),
    (96300199, 'CAGUAS FERNANDEZ', 'CESAR EDUARDO', 'CESAR EDUARDO CAGUAS FERNANDEZ', 'TU MANTENEDOR', 'Mtto', 'LUIS GONZALO CHILLAN PILLAJO'),
    (96301749, 'SHIGUANO ACHANGA', 'CHRISTIAN FABIAN', 'CHRISTIAN FABIAN SHIGUANO ACHANGA', 'GENUINOS', 'L2', 'DIEGO VLADIMIR ORTIZ CENTENO'),
    (96300506, 'CONEJO GUAMAN', 'CHRISTIAN GEOVANNY', 'CHRISTIAN GEOVANNY CONEJO GUAMAN', 'TEC', 'L1', 'DIEGO ARMANDO QUIÑA CABASCANGO'),
    (96300167, 'JURADO GALEANO', 'CHRISTIAN JAVIER', 'CHRISTIAN JAVIER JURADO GALEANO', 'ASES', 'L2', 'GONZALO VICENTE PEREZ CASERES'),
    (96307624, 'VERGARA ROJAS', 'CRISTHIAN DAVID', 'CRISTHIAN DAVID VERGARA ROJAS', 'TEC', 'L1', 'DIEGO ARMANDO QUIÑA CABASCANGO'),
    (96300217, 'BALCAZAR PINEDA', 'CRISTIAN PATRICIO', 'CRISTIAN PATRICIO BALCAZAR PINEDA', 'TEC', 'L1', 'DIEGO ARMANDO QUIÑA CABASCANGO'),
    (96301778, 'TIPAN PILAQUINGA', 'DANIEL MAURICIO', 'DANIEL MAURICIO TIPAN PILAQUINGA', 'GENUINOS', 'L2', 'DIEGO VLADIMIR ORTIZ CENTENO'),
    (96302655, 'CHIPANTAXI YACELGA', 'DANNY JAVIER', 'DANNY JAVIER CHIPANTAXI YACELGA', 'TEC', 'L1', 'DIEGO ARMANDO QUIÑA CABASCANGO'),
    (96300531, 'GUALLICHICO NARVAEZ', 'DARWIN DARIO', 'DARWIN DARIO GUALLICHICO NARVAEZ', 'GENUINOS', 'L2', 'DIEGO VLADIMIR ORTIZ CENTENO'),
    (96300993, 'PARIGUAMAN QUILUMBA', 'DARWIN JAVIER', 'DARWIN JAVIER PARIGUAMAN QUILUMBA', 'GENUINOS', 'L2', 'DIEGO VLADIMIR ORTIZ CENTENO'),
    (96300367, 'BRAVO SALAZAR', 'DARWIN RAUL', 'DARWIN RAUL BRAVO SALAZAR', 'GENUINOS', 'L2', 'GONZALO VICENTE PEREZ CASERES'),
    (96308328, 'QUISHPE USHIÑA', 'CHARLES BRANDON', 'CHARLES BRANDON  QUISHPE USHIÑA', 'FILLERS', 'L2', 'SANTIAGO JAVIER LLAMATUMBI MUÑOZ'),
    (96308273, 'GUERRERO GUASHPA', 'VERONICA DALILA', 'VERONICA DALILA GUERRERO GUASHPA', 'GENUINOS', 'L2', 'DIEGO VLADIMIR ORTIZ CENTENO'),
    (96300893, 'CHUQUI GUALOCHICO', 'EDGAR GUSTAVO', 'EDGAR GUSTAVO CHUQUI GUALOCHICO', 'PREMIUM', 'L2', 'SEGUNDO CLAUDIO MOROCHO YADAICELA'),
    (96300716, 'MENDOZA YANEZ', 'EDGAR RENE', 'EDGAR RENE MENDOZA YANEZ', 'GENUINOS', 'L2', 'DIEGO VLADIMIR ORTIZ CENTENO'),
    (96301930, 'CACUANGO CUATUCUAMBA', 'EDWIN DANIEL', 'EDWIN DANIEL CACUANGO CUATUCUAMBA', 'PREMIUM', 'L2', 'SEGUNDO CLAUDIO MOROCHO YADAICELA'),
    (96304015, 'CHILLAN SULCA', 'FRANCISCO JAVIER', 'FRANCISCO JAVIER  CHILLAN SULCA', 'ASES', 'L2', 'GONZALO VICENTE PEREZ CASERES'),
    (96300351, 'ERAZO SALAS', 'FRANKLIN MARCELO', 'FRANKLIN MARCELO ERAZO SALAS', 'FILLERS', 'L2', 'SANTIAGO JAVIER LLAMATUMBI MUÑOZ'),
    (96300255, 'LINCANGO MONTERO', 'HENRY MAURICIO', 'HENRY MAURICIO LINCANGO MONTERO', 'TEC', 'L2', 'GONZALO VICENTE PEREZ CASERES'),
    (96303760, 'CARVAJAL CABEZAS', 'HENRY MAURICIO', 'HENRY MAURICIO CARVAJAL CABEZAS', 'FILLERS', 'L2', 'SANTIAGO JAVIER LLAMATUMBI MUÑOZ'),
    (96301730, 'SANGOLUIZA PALLO', 'HENRY MAURICIO', 'HENRY MAURICIO SANGOLUIZA PALLO', 'ASES', 'L2', 'GONZALO VICENTE PEREZ CASERES'),
    (96307636, 'VALDIVIEZO AREAS', 'HOOBER AUGUSTO', 'HOOBER AUGUSTO VALDIVIEZO AREAS', 'PREMIUM', 'L2', 'SEGUNDO CLAUDIO MOROCHO YADAICELA'),
    (96300169, 'TUSA TARAPUEZ', 'JAIME DIOMEDES', 'JAIME DIOMEDES TUSA TARAPUEZ', 'FILLERS', 'L2', 'SANTIAGO JAVIER LLAMATUMBI MUÑOZ'),
    (96300227, 'ORTEGA JUMA', 'JAVIER RUBEN', 'JAVIER RUBEN ORTEGA JUMA', 'PREMIUM', 'L2', 'SEGUNDO CLAUDIO MOROCHO YADAICELA'),
    (96303762, 'CHAFUEL CADENA', 'JEFFERSON ALEXANDER', 'JEFFERSON ALEXANDER CHAFUEL CADENA', 'FILLERS', 'L2', 'SANTIAGO JAVIER LLAMATUMBI MUÑOZ'),
    (96300505, 'JIMENEZ JUMBO', 'JHONNY GERARDO', 'JHONNY GERARDO JIMENEZ JUMBO', 'TEC', 'L1', 'DIEGO ARMANDO QUIÑA CABASCANGO'),
    (96301731, 'FERNANDEZ PAUCAR', 'JHONY PATRICIO', 'JHONY PATRICIO FERNANDEZ PAUCAR', 'ASES', 'L2', 'GONZALO VICENTE PEREZ CASERES'),
    (96303502, 'PAUCAR IZA', 'JONATHAN XAVIER', 'JONATHAN XAVIER PAUCAR IZA', 'LOBOS', 'L1', 'PABLO SEBASTIAN BUSE VELASQUEZ'),
    (96300847, 'TEJADA ROBLES', 'JORGE ALBERTO', 'JORGE ALBERTO TEJADA ROBLES', 'TEC', 'L1', 'DIEGO ARMANDO QUIÑA CABASCANGO'),
    (96300994, 'MORALES ALMACHE', 'JORGE SANTIAGO', 'JORGE SANTIAGO MORALES ALMACHE', 'LOBOS', 'L1', 'PABLO SEBASTIAN BUSE VELASQUEZ'),
    (96300530, 'AZAÑA GUAMBI', 'JOSE LORENZO', 'JOSE LORENZO AZAÑA GUAMBI', 'FILLERS', 'L2', 'SANTIAGO JAVIER LLAMATUMBI MUÑOZ'),
    (96302253, 'MAZA OCHOA', 'JOSE LUIS', 'JOSE LUIS MAZA OCHOA', 'TEC', 'L1', 'DIEGO ARMANDO QUIÑA CABASCANGO'),
    (96300230, 'QUISHPE TACO', 'JUAN CARLOS', 'JUAN CARLOS QUISHPE TACO', 'LOBOS', 'L1', 'PABLO SEBASTIAN BUSE VELASQUEZ'),
    (96300204, 'JAUREGUI VILLAMARIN', 'LUCAS AUGUSTO', 'LUCAS AUGUSTO JAUREGUI VILLAMARIN', 'TEC', 'L1', 'DIEGO ARMANDO QUIÑA CABASCANGO'),
    (96302789, 'AYO CHIPANTASI', 'LUIS ALBERTO', 'LUIS ALBERTO AYO CHIPANTASI', 'PREMIUM', 'L2', 'DIEGO VLADIMIR ORTIZ CENTENO'),
    (96302885, 'CASIMANZA TORRES', 'LUIS EDUARDO', 'LUIS EDUARDO CASIMANZA TORRES', 'FILLERS', 'L2', 'SANTIAGO JAVIER LLAMATUMBI MUÑOZ'),
    (96300263, 'HERNANDEZ BENAVIDES', 'LUIS HORLANDO', 'LUIS HORLANDO HERNANDEZ BENAVIDES', 'GENUINOS', 'L1', 'DIEGO VLADIMIR ORTIZ CENTENO'),
    (96302234, 'PILLAJO GUANO', 'LUIS PAUL', 'LUIS PAUL PILLAJO GUANO', 'ASES', 'L2', 'GONZALO VICENTE PEREZ CASERES'),
    (96300244, 'QUISHPE SULCA', 'LUIS WILMER', 'LUIS WILMER QUISHPE SULCA', 'TEC', 'L1', 'DIEGO ARMANDO QUIÑA CABASCANGO'),
    (96301729, 'TACO AMAYA', 'MARCO ANTONIO', 'MARCO ANTONIO TACO AMAYA', 'PREMIUM', 'L2', 'SEGUNDO CLAUDIO MOROCHO YADAICELA'),
    (96301854, 'SHUGULI CHAPA', 'MARCO SANTIAGO', 'MARCO SANTIAGO SHUGULI CHAPA', 'GENUINOS', 'L2', 'DIEGO VLADIMIR ORTIZ CENTENO'),
    (96304013, 'TUTILLO OÑA', 'MARIO AMADOR', 'MARIO AMADOR TUTILLO OÑA', 'TU MANTENEDOR', 'Mtto', 'DIEGO VLADIMIR ORTIZ CENTENO'),
    (96300229, 'AZAÑA QUILUMBA', 'MARIO FABIAN', 'MARIO FABIAN AZAÑA QUILUMBA', 'LOBOS', 'L1', 'PABLO SEBASTIAN BUSE VELASQUEZ'),
    (96303136, 'LEMA CASTILLO', 'MARIO SANTIAGO', 'MARIO SANTIAGO LEMA CASTILLO', 'LOBOS', 'L1', 'PABLO SEBASTIAN BUSE VELASQUEZ'),
    (96307380, 'CHILLAN SULCA', 'MIGUEL ANGEL', 'MIGUEL ANGEL CHILLAN SULCA', 'GENUINOS', 'L2', 'DIEGO VLADIMIR ORTIZ CENTENO'),
    (96300185, 'TOAPANTA CUSHI', 'MIGUEL ANGEL', 'MIGUEL ANGEL TOAPANTA CUSHI', 'PREMIUM', 'L2', 'SEGUNDO CLAUDIO MOROCHO YADAICELA'),
    (96300350, 'QUINTANA OSEJO', 'OSCAR MAURICIO', 'OSCAR MAURICIO QUINTANA OSEJO', 'LOBOS', 'L1', 'PABLO SEBASTIAN BUSE VELASQUEZ'),
    (96300205, 'ESTEVEZ DOMINGUEZ', 'PAUL RENAN', 'PAUL RENAN ESTEVEZ DOMINGUEZ', 'LOBOS', 'L1', 'PABLO SEBASTIAN BUSE VELASQUEZ'),
    (96300232, 'SANTAMARIA MEJIA', 'ROBERTO JAVIER', 'ROBERTO JAVIER SANTAMARIA MEJIA', 'TEC', 'L1', 'DIEGO ARMANDO QUIÑA CABASCANGO'),
    (96301058, 'PILCO TITUANA', 'RODRIGO XAVIER', 'RODRIGO XAVIER PILCO TITUANA', 'ASES', 'L2', 'GONZALO VICENTE PEREZ CASERES'),
    (96302255, 'TONATO PACHECO', 'ROLANDO MARCELO', 'ROLANDO MARCELO TONATO PACHECO', 'ASES', 'L2', 'GONZALO VICENTE PEREZ CASERES'),
    (96307629, 'FIGUEROA GUERRERO', 'RUBEN JOSE', 'RUBEN JOSE FIGUEROA GUERRERO', 'TU MANTENEDOR', 'Mtto', 'DIEGO VLADIMIR ORTIZ CENTENO'),
    (96300238, 'OSCULLO GUAÑA', 'SANTIAGO JAVIER', 'SANTIAGO JAVIER OSCULLO GUAÑA', 'FILLERS', 'L2', 'SANTIAGO JAVIER LLAMATUMBI MUÑOZ'),
    (96300256, 'TOAPANTA QUIÑA', 'SEGUNDO RICARDO', 'SEGUNDO RICARDO TOAPANTA QUIÑA', 'PREMIUM', 'L2', 'SEGUNDO CLAUDIO MOROCHO YADAICELA'),
    (96300529, 'CHASI TONATO', 'SILVIO ADAN', 'SILVIO ADAN CHASI TONATO', 'GENUINOS', 'L2', 'DIEGO VLADIMIR ORTIZ CENTENO'),
    (96303673, 'SANTIN GUEVARA', 'STALIN MANUEL', 'STALIN MANUEL SANTIN GUEVARA', 'FILLERS', 'L2', 'SANTIAGO JAVIER LLAMATUMBI MUÑOZ'),
    (96303139, 'TARAPUEZ LOPEZ', 'TATIANA CAROLINA', 'TATIANA CAROLINA TARAPUEZ LOPEZ', 'ASES', 'L2', 'GONZALO VICENTE PEREZ CASERES'),
    (96300502, 'CARBO CANTERAL', 'VICENTE ENRIQUE', 'VICENTE ENRIQUE CARBO CANTERAL', 'GENUINOS', 'L2', 'DIEGO VLADIMIR ORTIZ CENTENO'),
    (96300478, 'SIMBAÑA LINCANGO', 'VICTOR MAURICIO', 'VICTOR MAURICIO SIMBAÑA LINCANGO', 'ASES', 'L2', 'GONZALO VICENTE PEREZ CASERES'),
    (96300228, 'AIMACAÑA ESCOBAR', 'WASHINGTON FERNANDO', 'WASHINGTON FERNANDO AIMACAÑA ESCOBAR', 'ASES', 'L2', 'GONZALO VICENTE PEREZ CASERES'),
    (96300239, 'PISUNA QUINCHIMBLA', 'WILFRIDO', 'WILFRIDO PISUNA QUINCHIMBLA', 'PREMIUM', 'L2', 'SEGUNDO CLAUDIO MOROCHO YADAICELA'),
    (96300172, 'JIMENEZ JIMENEZ', 'WUALTER RENE', 'WUALTER RENE JIMENEZ JIMENEZ', 'FILLERS', 'L2', 'SANTIAGO JAVIER LLAMATUMBI MUÑOZ'),
    (96301750, 'VEINTIMILLA HIDALGO', 'BYRON ANDRES', 'BYRON ANDRES VEINTIMILLA HIDALGO', 'TU MANTENEDOR', 'Mtto', 'LUIS FERNANDO SIMBAÑA SIERRA'),
    (96300892, 'SANTIANA VERGARA', 'FERNANDO ANDRES', 'FERNANDO ANDRES SANTIANA VERGARA', 'TU MANTENEDOR', 'Mtto', 'LUIS FERNANDO SIMBAÑA SIERRA'),
    (96300198, 'CADENA LLAMUCA', 'DAVID ROBERTO', 'DAVID ROBERTO CADENA LLAMUCA', 'TU MANTENEDOR', 'Mtto', 'LUIS FERNANDO SIMBAÑA SIERRA'),
    (96300201, 'CHILLAN SACANCELA', 'LUIS EDGAR', 'LUIS EDGAR CHILLAN SACANCELA', 'TU MANTENEDOR', 'Mtto', 'LUIS FERNANDO SIMBAÑA SIERRA'),
    (96300209, 'CHILLAN CACHAGO', 'LUIS KLEVER', 'LUIS KLEVER CHILLAN CACHAGO', 'TU MANTENEDOR', 'Mtto', 'LUIS FERNANDO SIMBAÑA SIERRA'),
    (96300224, 'SUASNAVAS FLORES', 'WILLIAM PATRICIO', 'WILLIAM PATRICIO SUASNAVAS FLORES', 'TU MANTENEDOR', 'Mtto', 'LUIS GONZALO CHILLAN PILLAJO'),
    (96300231, 'PAILLACHO QUISHPE', 'CESAR EDUARDO', 'CESAR EDUARDO PAILLACHO QUISHPE', 'TU MANTENEDOR', 'Mtto', 'LUIS FERNANDO SIMBAÑA SIERRA'),
    (96300241, 'SORIA REINOSO', 'MIGUEL GERARDO', 'MIGUEL GERARDO SORIA REINOSO', 'TU MANTENEDOR', 'Mtto', 'LUIS FERNANDO SIMBAÑA SIERRA'),
    (96300352, 'SANTILLAN GALARZA', 'HOLGER ROLANDO', 'HOLGER ROLANDO SANTILLAN GALARZA', 'TU MANTENEDOR', 'Mtto', 'LUIS GONZALO CHILLAN PILLAJO'),
    (96300527, 'SANCHEZ TIPAN', 'JORGE ALBERTO', 'JORGE ALBERTO SANCHEZ TIPAN', 'TU MANTENEDOR', 'Mtto', 'LUIS GONZALO CHILLAN PILLAJO'),
    (96300768, 'PILICITA JACOME', 'DARWIN FABIAN', 'DARWIN FABIAN PILICITA JACOME', 'TU MANTENEDOR', 'Mtto', 'LUIS GONZALO CHILLAN PILLAJO'),
    (96301802, 'CEDEÑO ANZULES', 'HENRY ALEJANDRO', 'HENRY ALEJANDRO CEDEÑO ANZULES', 'TU MANTENEDOR', 'Mtto', 'LUIS GONZALO CHILLAN PILLAJO'),
    (96308382, 'JOSE GUILLERMO', 'BAILON MOREIRA', 'BAILON MOREIRA JOSE GUILLERMO', 'LOBOS', 'L1', 'PABLO SEBASTIAN BUSE VELASQUEZ'),
    (96308843, 'CAROLINA ELIZABETH', 'CALAHORRANO CISNEROS', 'CALAHORRANO CISNEROS CAROLINA ELIZABETH', 'ASES', 'L2', 'GONZALO VICENTE PEREZ CASERES'),
    (96308844, 'JOHNY RODRIGO', 'IZA PICHO', 'IZA PICHO JOHNY RODRIGO', 'GENUINOS', 'L2', 'DIEGO VLADIMIR ORTIZ CENTENO')
ON CONFLICT (numero_sharp) DO UPDATE SET
    apellido = EXCLUDED.apellido,
    nombre = EXCLUDED.nombre,
    nombre_completo = EXCLUDED.nombre_completo,
    equipo = EXCLUDED.equipo,
    linea = EXCLUDED.linea,
    lider_nombre = EXCLUDED.lider_nombre,
    updated_at = NOW();
